import "./globals.css";
import Nav from "./component/nav";
import Footer from "./component/footer";
import Template from "./template";
import SplashScreen from "./splacescreen";
import { ThemeProvider } from "./context/theme-context";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressContentEditableWarning>
      <body
        className="flex flex-col min-h-screen bg-gradient-to-br from-white via-blue-50 to-blue-100"
      >
        <SplashScreen>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <Nav />
            {/* <Template> */}
              {children}
            {/* </Template> */}
            <Footer />
          </ThemeProvider>
        </SplashScreen>
      </body>
    </html>
  );
}
